### ISSUE TITLE
Ridiculous memory and CPU usage. Unable to load into the game

### ISSUE THREAD

**Issue by neon-age** [Unity-Technologies/ECS-Network-Racing-Sample#1]
I've got a pretty weak laptop with 12GB of old 1600mhz DDR3.
I was able to open the game menu, but loading into an actual game seems to be not an option for me.

![image](https://user-images.githubusercontent.com/29812914/210056545-ef78a378-b7c4-432d-9098-33330585223a.png)

After waiting for about 10 minutes, with SSD running at 500mb/s for a few minutes, and then being stale - Loading text showed up!
And then this happened...
![image](https://user-images.githubusercontent.com/29812914/210057132-181af3b2-f4ea-4e42-b16c-f01ba56f9543.png)
So I had to shut it down to not kill my hardware.

Deleting EVERY texture from the project seemed to help, but still far from ideal.
![image](https://user-images.githubusercontent.com/29812914/210058263-2e9dcd23-f67c-437d-b1a8-475829d1daa8.png)

Especially for the fact that it barely runs, jumping from 10 to 25 fps, very inconsistently. 
![image](https://user-images.githubusercontent.com/29812914/210062139-7ab2f11b-3fc0-4379-a9dc-448531d83405.png)
Sometimes vehicle even flips due to frame drops.

And before Burst compiled, it was less than 2 fps... (while Main Menu is fine, as there is no Physics systems)
![image](https://user-images.githubusercontent.com/29812914/210059449-a421e40d-1ca8-48a7-b5e2-f8cfade6f08d.png)

Profiler shows that it's due to Unity Physics simulation.
![image](https://user-images.githubusercontent.com/29812914/210063077-b434798c-4284-4c3c-b307-29c7406b3ede.png)
![image](https://user-images.githubusercontent.com/29812914/210058882-7e8499af-3eda-4201-88ed-4c6fbba735e7.png)

**Comment by julianunity** [comment]
Please try the updated version on Unity 6, which includes improvements and script updates in the latest commit.
Be sure to clone the project rather than downloading it directly.
I look forward to your feedback and will be available for any questions.
